---
env:
  contexts:
    - name: baseline
      urls:
        - http://host.docker.internal:8082
      excludePaths: []

  parameters:
    failOnError: true
    progressToStdout: false

jobs:
  - type: passiveScan-config
    parameters:
      enableTags: false
      maxAlertsPerRule: 10

  - type: spider
    parameters:
      url: http://host.docker.internal:8082
      maxDuration: 1

  - type: passiveScan-wait
    parameters:
      maxDuration: 0

  - type: outputSummary
    parameters:
      format: Long
      summaryFile: /home/zap/zap_out.json
    rules: []

  - type: report
    parameters:
      reportDir: /zap/wrk/
      reportFile: rapport.html
      reportTitle: ZAP Scanning Report
      reportDescription: ""
      template: traditional-html

  - type: report
    parameters:
      reportDir: /zap/wrk/
      reportFile: rapport.json
      reportTitle: ZAP Scanning Report
      reportDescription: ""
      template: traditional-json