name: DevSecOps Pipeline

on:
  push:

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my-app .

      - name: Trivy FS Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          format: table
          exit-code: 0
          skip-dirs: .git
          skip-files: .env

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: my-app
          format: table
          exit-code: 0

      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v3

      - name: Conftest Policy Check
        run: |
          docker run --rm -v $(pwd):/project instrumenta/conftest test k8s/
